# Generated by Django 4.1.6 on 2023-03-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profile_bio_remove_profile_birthdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
