# Generated by Django 4.1.6 on 2023-03-21 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authorization', '0006_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customuseruserpermissions',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customuseruserpermissions',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='customuseruserpermissions',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='users', to='auth.permission'),
        ),
        migrations.DeleteModel(
            name='CustomUserGroups',
        ),
        migrations.DeleteModel(
            name='CustomUserUserPermissions',
        ),
    ]
